#!/bin/bash

mkdir -p logs err

TYPE="parallel"
CORE_AMOUNT=6

JOB_NAME="lab3_3_$TYPE_$CORE_AMOUNT"
PROJECT_NAME="mothm_lab3_3"
LOG_FILE="lab3_3_$TYPE_$CORE_AMOUNT.log"
LOG_PATH="logs/$LOG_FILE"
ERR_PATH="err/$LOG_FILE"

#BSUB -J $JOB_NAME
#BSUB -P $PROJECT_NAME
#BSUB -W 08:00
#BSUB -n 1
#BSUB -oo $LOG_PATH
#BSUB -eo $ERR_PATH

export ARRAY_SIZE=4000000
export CYCLES=10

time mpiexec -n "$CORE_AMOUNT" "./program_$TYPE"
